-- GERA - schema PostgreSQL 15+ / Supabase. Dados reais nao sao versionados.
BEGIN;

CREATE TABLE IF NOT EXISTS instrutores (
  id_instrutor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255) NOT NULL CHECK (length(trim(nome)) BETWEEN 2 AND 255),
  matricula varchar(20) NOT NULL UNIQUE CHECK (matricula ~ '^[0-9]+$')
);

CREATE TABLE IF NOT EXISTS salas (
  id_sala integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255) NOT NULL CHECK (length(trim(nome)) BETWEEN 1 AND 255),
  bloco varchar(50) NOT NULL DEFAULT 'A',
  tipo varchar(20) NOT NULL DEFAULT 'SALA' CHECK (tipo IN ('SALA', 'LABORATORIO')),
  UNIQUE (nome, bloco)
);

CREATE TABLE IF NOT EXISTS turmas (
  id_turma integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255) NOT NULL CHECK (length(trim(nome)) BETWEEN 2 AND 255),
  turno varchar(10) NOT NULL DEFAULT 'Manhã' CHECK (turno IN ('Manhã', 'Tarde', 'Noite')),
  UNIQUE (nome, turno)
);

CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(254) NOT NULL UNIQUE CHECK (email = lower(trim(email))),
  senha varchar(255) NOT NULL CHECK (senha ~ '^\$2[aby]\$'),
  nome varchar(255) NOT NULL,
  perfil varchar(20) NOT NULL DEFAULT 'instrutor' CHECK (perfil IN ('admin', 'instrutor', 'tv')),
  primeiro_acesso boolean NOT NULL DEFAULT true,
  ativo boolean NOT NULL DEFAULT true,
  tentativas_login smallint NOT NULL DEFAULT 0 CHECK (tentativas_login BETWEEN 0 AND 20),
  bloqueado_ate timestamptz,
  token_version integer NOT NULL DEFAULT 0,
  senha_alterada_em timestamptz,
  id_instrutor_vinculado integer UNIQUE REFERENCES instrutores(id_instrutor) ON DELETE CASCADE,
  CONSTRAINT usuario_instrutor_coerente CHECK (
    (perfil = 'instrutor' AND id_instrutor_vinculado IS NOT NULL)
    OR (perfil IN ('admin', 'tv') AND id_instrutor_vinculado IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS alocacoes (
  id_alocacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_instrutor integer NOT NULL REFERENCES instrutores(id_instrutor) ON DELETE CASCADE,
  id_sala integer NOT NULL REFERENCES salas(id_sala) ON DELETE CASCADE,
  id_turma integer NOT NULL REFERENCES turmas(id_turma) ON DELETE CASCADE,
  turno varchar(10) NOT NULL CHECK (turno IN ('Manhã', 'Tarde', 'Noite')),
  data_inicio date NOT NULL,
  data_fim date NOT NULL,
  criado_por_perfil varchar(20) NOT NULL DEFAULT 'admin' CHECK (criado_por_perfil IN ('admin', 'instrutor')),
  criado_por_usuario integer REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  CHECK (data_inicio <= data_fim)
);

CREATE TABLE IF NOT EXISTS notificacoes (
  id_notificacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_instrutor integer NOT NULL REFERENCES instrutores(id_instrutor) ON DELETE CASCADE,
  mensagem text NOT NULL CHECK (length(mensagem) BETWEEN 1 AND 2000),
  lida boolean NOT NULL DEFAULT false,
  data_criacao timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS transferencias_pendentes (
  id_transferencia integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_alocacao_original integer NOT NULL REFERENCES alocacoes(id_alocacao) ON DELETE CASCADE,
  id_instrutor_origem integer NOT NULL REFERENCES instrutores(id_instrutor) ON DELETE CASCADE,
  id_instrutor_destino integer NOT NULL REFERENCES instrutores(id_instrutor) ON DELETE CASCADE,
  data_inicio_transferencia date NOT NULL,
  data_fim_transferencia date NOT NULL,
  status varchar(10) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aceita', 'rejeitada')),
  data_criacao timestamptz NOT NULL DEFAULT now(),
  data_atualizacao timestamptz NOT NULL DEFAULT now(),
  CHECK (id_instrutor_origem <> id_instrutor_destino),
  CHECK (data_inicio_transferencia <= data_fim_transferencia)
);

CREATE INDEX IF NOT EXISTS idx_alocacoes_sala_periodo ON alocacoes (id_sala, turno, data_inicio, data_fim);
CREATE INDEX IF NOT EXISTS idx_alocacoes_instrutor_periodo ON alocacoes (id_instrutor, turno, data_inicio, data_fim);
CREATE INDEX IF NOT EXISTS idx_alocacoes_turma_periodo ON alocacoes (id_turma, turno, data_inicio, data_fim);
CREATE INDEX IF NOT EXISTS idx_notificacoes_instrutor_lida ON notificacoes (id_instrutor, lida, data_criacao DESC);
CREATE INDEX IF NOT EXISTS idx_transferencias_destino_status ON transferencias_pendentes (id_instrutor_destino, status, data_criacao DESC);

CREATE OR REPLACE FUNCTION atualizar_data_atualizacao() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.data_atualizacao = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_transferencias_atualizacao ON transferencias_pendentes;
CREATE TRIGGER trg_transferencias_atualizacao BEFORE UPDATE ON transferencias_pendentes
FOR EACH ROW EXECUTE FUNCTION atualizar_data_atualizacao();

-- A API usa a conexao PostgreSQL privada; anon/authenticated nao recebem politicas.
ALTER TABLE instrutores ENABLE ROW LEVEL SECURITY;
ALTER TABLE salas ENABLE ROW LEVEL SECURITY;
ALTER TABLE turmas ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE alocacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE notificacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE transferencias_pendentes ENABLE ROW LEVEL SECURITY;

COMMIT;
